feat: searching tools
Kojot999/gamebase pull request #6
Opened 2022-05-25 15:00 UTC by Kojot999

2022-05-25 15:07 UTC, pislagz requested changes

2022-05-25 15:07 UTC, pislagz commented on src/app/api/api.js
> +  console.log(result);
delete

2022-05-25 15:07 UTC, pislagz commented on src/app/api/games/index.js
> +  // to pojdzie do queryBuildera
delete

2022-05-26 08:42 UTC, Kojot999 commented on src/app/api/api.js
> +  console.log(result);
done

2022-05-26 08:42 UTC, Kojot999 commented on src/app/api/games/index.js
> +  // to pojdzie do queryBuildera
done

2022-05-26 08:45 UTC, merged